### ISSUE TITLE
Add to Melpa

### ISSUE THREAD

**Issue by edmundmiller** [Emiller88/emacs-doom-community-themes#1]

**Comment by flatwhatson** [comment]
https://github.com/melpa/melpa/pull/6324

**Comment by flatwhatson** [comment]
Closing, we're merging to `doom-themes` instead.

**Comment by ema2159** [comment]
Is worth to mention that I've found some little things in Gruvbox and Palenight/Moonlight themes like the Ivy posframe face. Also I think we should change the modeline face in Palenight/Moonlight given it's too dark
