### ISSUE TITLE
Solarized Dark

### ISSUE THREAD

**Issue by ema2159** [Emiller88/emacs-doom-community-themes#3]
Hi! I saw you took my implementation of Solarized Dark from my Doom themes PR. I have no problem with it (just make sure to give credit to me and also to the other authors from the other PRs), but I think you should at least ask before you take someones work! As I said, I have no problem, just take that into consideration for the next time.

**Comment by flatwhatson** [comment]
Thanks @ema2159, and apologies, you are right that we should have sought your approval.

This project is a good-faith effort to remove some workload from Henrik and get themes merged & released to the community more rapidly.  It was never our intention to take credit for your work.  You'll note that you are listed as the author of the solarized dark theme in the git log, as are all the other authors.  This information will soon be included in the README as well.

Thanks again for your contribution!

**Comment by ema2159** [comment]
Thanks! No worries, I'm cool with it, it's just a heads up, some people may not be so cool with it and may get upset. Have a nice week! :D

**Comment by edmundmiller** [comment]
@ema2159 Thanks for reaching out! There was no ill intent, I added you as a co-author in 1395867 (I'm not sure if that was best practice though since we hadn't dicussed it). Come join us in the [discord](https://discordapp.com/invite/bcZ6P3y) so I have somewhere to reach out to you in the future!

**Comment by ema2159** [comment]
Don't worry @Emiller88 , I know there was no bad intention! Please check this discussion: https://github.com/ema2159/muse-themes/issues/3 and hopefully you can tell me what you think. I haven't used Discord before so I'll have to figure it out!
